name: ci
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.5
  - cryptography=37.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - flit-core=3.7.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.8.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - libffi=3.4.2
  - libsodium=1.0.18
  - libzlib=1.2.12
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openpyxl=3.0.9
  - openssl=1.1.1p
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=21.2.4
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytz=2022.1
  - pywin32=302
  - pywinpty=2.0.2
  - pyzmq=22.3.0
  - requests=2.28.0
  - send2trash=1.8.0
  - setuptools=61.2.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.6.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - vc=14.2
  - voila=0.3.5
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - websockets=10.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - pip:
    - lxml==4.9.0
    - multitasking==0.0.11
    - yfinance==0.1.72

